services:

  cryptoapi:
    build:
      context: ./src/crypto_api
      dockerfile: Dockerfile
    ports:
      - "4545:4545"
    environment:
      - MINIO_ACCESS_KEY_ID=your_access_key_id
      - MINIO_SECRET_ACCESS_KEY=your_secret_access_key
      - MINIO_ENDPOINT=your_host_ip:9000
      - MINIO_BUCKET_NAME=your_bucket
      - DB_HOST=your_host_ip
      - DB_USER=root
      - DB_PASS=root
      - DB_PORT=5432
      - DB_NAME=CryptoScraper
    depends_on:
      - pgdatabase
      - minio

  pgdatabase:
    image: postgres:17    
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=CryptoScraper
    volumes:
      - "./volumes/postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./volumes/pgadmin:/var/lib/pgadmin:rw"
    ports:
      - "8081:80"

  minio:
    image: quay.io/minio/minio
    container_name: minio_server
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./volumes/minio_data:/data"